genesis_id = ""
system = "Electroneum"
dependencies = ["independent"]
icon = "electroneum"

[token]
name = "electroneum token"
symbol = "ETN"

[consensus]
consensus_type = ""
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptocurrency"
headline = "Mobile Cryptocurrency, powered by an app"

[crowdsales]
start_date = "2017-09-14T00:01:00"
end_date = "2017-10-31T11:59:00"
end_date_plan = "2017-10-31T11:59:00"
genesis_address = [""]
funding_terms = "http://electroneum.com/terms/"
funding_url = "http://electroneum.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "electroneum.com"
url = "http://electroneum.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Electroneum Whitepaper"
url = "http://electroneum.com/overview-white-paper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "paper"
name = "Electroneum Technical Whitepaper"
url = "http://electroneum.com/technical-white-paper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Electroneum GitHub"
url = "https://github.com/electroneum"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Electroneum Blog"
url = "http://electroneum.com/blog/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2065043.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/electroneum"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Electroneum Telegram"
url = "https://telegram.me/electroneum"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Electroneum Slack"
url = "https://electroneum.slack.com/join/shared_invite/MjIyMjE0MDU1NDg4LTE1MDIwNDgxNTktZTg5NWY4YWRjYQ"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/electroneum"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCEQvcgq9-mtqdYEM3B9y_-g"
icon = "youtube.png"
tags = ["News"]
